train:
  _target_: src.datasets.HardTokenCheckpointDataset
  checkpoint_path: null
  max_sequences: null
val:
  _target_: src.datasets.TinyStoriesByteDataset
  split: "train"
  sequence_length: ${model.max_seq_len}
  skip_texts: 10000
  max_texts: 3000
  max_sequences: null
  streaming: true
  hf_cache_dir: null
  data_dir: "data/tinystories_byte"
  local_text_path: null
  use_cache: true

test:
  _target_: src.datasets.TinyStoriesByteDataset
  split: "train"
  sequence_length: ${model.max_seq_len}
  skip_texts: 13000
  max_texts: 2000
  max_sequences: null
  streaming: true
  hf_cache_dir: null
  data_dir: "data/tinystories_byte"
  local_text_path: null
  use_cache: true
