defaults:
  - tinystories_lm_softdistill_local_bpe_1024
  - _self_

model:
  max_seq_len: 256
  d_model: 256
  n_heads: 8
  n_layers: 6
  dim_feedforward: 1024
  dropout: 0.0

datasets:
  val:
    sequence_length: ${model.max_seq_len}
  test:
    sequence_length: ${model.max_seq_len}
