defaults:
  - model: tiny_transformer_lm_local_bpe_1024
  - writer: noop
  - metrics: language_modeling
  - datasets: tinystories_softdistill_local_bpe_1024
  - dataloader: language_modeling
  - transforms: none
  - _self_

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.95
  step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.LanguageModelingLoss

trainer:
  log_step: 20
  n_epochs: 5
  epoch_len: 64
  device_tensors: ["input_ids", "labels", "target_probs", "attention_mask"]
  resume_from: null
  device: auto
  override: True
  save_only_best: false
  monitor: "min val_Perplexity"
  save_period: 1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
  max_grad_norm: 1.0
